default_install_hook_types = ["pre-commit", "pre-push"]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "format"
name = "make format"
language = "system"
entry = "make format"
pass_filenames = false
always_run = true
stages = ["pre-commit"]

[[repos.hooks]]
id = "lint"
name = "make lint"
language = "system"
entry = "make lint"
pass_filenames = false
always_run = true
stages = ["pre-commit"]

[[repos.hooks]]
id = "typecheck"
name = "make typecheck"
language = "system"
entry = "make typecheck"
pass_filenames = false
always_run = true
stages = ["pre-push"]

[[repos.hooks]]
id = "test"
name = "make test"
language = "system"
entry = "make test"
pass_filenames = false
always_run = true
stages = ["pre-push"]
